version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/devops/containers/sfdx-vlocity/node-packages/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "/devops/containers/sfdx-vlocity/sfdx-plugins/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
